export const API_END_POINTS = {
    users: 'users',
    user: 'user',
    assessment: 'assessment',
    assessments: 'assessments',
    constructs: 'constructs',
    construct: 'construct',
    user_model_formulas: 'usermodelformulas',
    user_model_formula: 'usermodelformula',
    orders:'orders',
    order_status:'order/status',
    products: 'products',
    product:'product',
    signed_url:'product/file',
    assessment_signed_url:'assessment/get-signed-url',
    product_file_delete:'product/file',
    companies: 'company-structure/organizations',
    company: 'company-structure/organization',
    intervention:'intervention',
    interventions:'interventions',
    send_invitation:'email-invitation',
    pattern_details:'patterns-detail',
    pattern_details_by_id:'pattern-detail',
    pattern_details_intervention: 'pattern-detail/interventions',
}